'''
Configuration file for all 'Kinesis Functions'
'''

STREAM_NAME = '<KINESIS_STATUS_DATA_STREAM>'
API_BASE_URL = '<API_GATEWAY_KINESIS>'
BASE_URL = API_BASE_URL + '/streams/'

HTTP = 'http://'
WORKFLOW_HOSTNAME = "<WORKFLOW_HOSTNAME>"
WORKFLOW_PORT = "<WORKFLOW_PORT>"
WORKFLOW_SIGNATURE = '/patient-status/update-patient-state/'
WORKFLOW_API = HTTP + WORKFLOW_HOSTNAME + \
    ':' + WORKFLOW_PORT + WORKFLOW_SIGNATURE

NLP_PING_SIGNATURE = '/nlp/mock-ping'
NLP_DATES_SIGNATURE = '/nlp/mock-invoke-nlp-dates/'
NLP_CODES_SIGNATURE = '/nlp/mock-invoke-nlp-codes/'
NLP_CODES_API = HTTP + WORKFLOW_HOSTNAME + ':' + WORKFLOW_PORT + NLP_CODES_SIGNATURE
NLP_DATES_API = HTTP + WORKFLOW_HOSTNAME + ':' + WORKFLOW_PORT + NLP_DATES_SIGNATURE
NLP_PING_API = HTTP + WORKFLOW_HOSTNAME + ':' + WORKFLOW_PORT + NLP_PING_SIGNATURE
